### ISSUE TITLE
Add onboarding information to the README

### ISSUE THREAD

**Issue by monocle** [All-Inclusive-Web-Team/forum-project#18]
It would be helpful for people who are interested in participating on the AIWT website to have a README with information on how to get up to speed with the current the project and things they could contribute to. Expecting people to read through all of the Discord discussion history is a bit cumbersome and is a barrier for newcomers who might be willing to get involved.

**Comment by adamwhitlock1** [comment]
I think this is a great idea. I just joined the community as well and I could certainly use some help knowing how I can help and  what the direction of the project is.

**Comment by monocle** [comment]
@ddowy If you're okay with moving to GH issues, I can submit a README PR. Basically, if anybody works on something there should be an GH issues to document what exactly they are working on so people can collaborate on that topic or avoid working on the same thing.

**Comment by mkgrtx** [comment]
You can also use project table

**Comment by ddowy** [comment]
@monocle Yeah for sure, do you mean make a different issue other than this thread for the README? We definitely can transition to gh issues.

**Comment by ddowy** [comment]
@mkgrtx project table? How does that look?

**Comment by mkgrtx** [comment]
@ddowy  I mean https://github.com/All-Inclusive-Web-Team/All-Inclusive-Web-Team.github.io/projects?query=is%3Aopen

**Comment by ddowy** [comment]
@mkgrtx gotcha I am still unaware of all the things that git has to offer, this is also a good option for tasks
