### ISSUE TITLE
Add .env-example to forum backend

### ISSUE THREAD

**Issue by adamwhitlock1** [All-Inclusive-Web-Team/forum-project#25]
**Description**

Looks like we are using some env variables in the server `db.js` file. I would suggest we add a .env-sample or .env-example type file to the repo so that devs know what the different env variables are that are needed for running the application. Then we should mention this in our docs for the project so that people know to copy that file and update it for use locally.

**Tasks**
- Update repo to include .env-example
- Update docs to mention using the sample file locally for setting up BE server

**Comment by ddowy** [comment]
Thank you for adding this, I will get this added in today.

**Comment by ddowy** [comment]
I have added a .env.defaults file so there will no longer be any need to set up a .env file
